# Generated by Django 3.1.1 on 2020-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
